name: Build app

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: Miljø versjon som skal brukes til bygg.
        default: 'ubuntu-latest'
      t-2c:
        required: false
        type: string
        description: Tråd konfig til maven.
        default: ''
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: '17'
      sonar-scan:
        required: false
        type: boolean
        description: Skal sonar scan brukes?
        default: false
      use-reader:
        required: false
        type: boolean
        description: Hvilket token skal brukes?
        default: false
    outputs:
      build-version:
        description: "Build version"
        value: ${{ jobs.build-and-test.outputs.build-version }}

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner.outputs.runner }}
    steps:
      - name: Velg runner basert på aktør som oppretter PR
        id: runner
        run: |
          if [ ${{ github.actor }} == 'dependabot[bot]' ]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          else
            echo "runner=${{ inputs.runs-on }}" >> $GITHUB_OUTPUT
          fi

  build-and-test:
    name: Build and test
    needs: [setup-runner]
    runs-on: ${{ needs.setup-runner.outputs.runner }}
    outputs:
      build-version: ${{ steps.generate-build-version.outputs.build-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
        with:
          fetch-depth: 0

      - name: Create maven .m2 settings for GITHUB
        if: ${{ !inputs.use-reader }}
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{"id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}",
              "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }}]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN}}" }]'
          output_file: settings.xml

      - name: Create maven .m2 settings for READER
        if: inputs.use-reader
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{"id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}",
              "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }}]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.READER_TOKEN}}" }]'
          output_file: settings.xml

      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate build version
        id: generate-build-version
        run: |
          echo "build-version=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Print build version
        run: echo "Generated build-version is ${{ steps.generate-build-version.outputs.build-version }}"

      - name: Build artifacts
        run: |
          echo "Building artifacts ${{ steps.generate-build-version.outputs.build-version }}"
          mvn versions:set -DnewVersion="${{ steps.generate-build-version.outputs.build-version }}" -s settings.xml -q -e -B
          mvn install -s settings.xml ${{ inputs.t-2c }} -q -e -B -Psonar

      - name: Sonar analyse
        if: (inputs.sonar-scan && github.actor != 'dependabot[bot]')
        run: |
          mvn jacoco:report jacoco:report-aggregate sonar:sonar -s settings.xml ${{ inputs.t-2c }} -e -q -B -Djacoco.destFile=$(pwd)/target/jacoco.exec -Psonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up generated stuff before caching
        run: |
          rm ~/.m2/repository/no/nav/foreldrepenger -r
