name: Deploy
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119)'
      cluster:
        required: true
        type: string
        description: 'The cluster to deploy to (dev-fss|dev-gcp|prod-fss|prod-gcp)'
      namespace:
        required: false
        type: string
        description: 'The namespace to deploy to'
        default: 'teamforeldrepenger'
      gar:
        required: false
        type: string
        description: 'The namespace to deploy to'
        default: 'false'
      naiserator_file:
        required: false
        type: string
        description: 'The naiserator.yaml file name in .deploy/ to use'
        default: 'naiserator.yaml'
      deploy_context:
        required: false
        type: string
        description: 'The deploy context /'
        default: ''
      image_suffix:
        required: false
        type: string
        description: 'The suffix of the image to be deployed'
        default: ''
      branch:
        required: false
        type: string
        description: Alternativ branch Ã¥ deploye fra

env:
  IMAGE: ${{ inputs.image }} # Brukes i naiserator.yaml
jobs:
  deploy:
    name: deploy
    environment: ${{ inputs.cluster }}:${{ inputs.namespace }}${{ inputs.image_suffix }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
        with:
          ref: ${{ (inputs.branch != '' && inputs.branch) || '' }}
      - name: Deploy ${{ inputs.cluster }} fra Github
        if: inputs.gar == 'false'
        uses: nais/deploy/actions/deploy@afaaf1c0eecfa18daad98677b9d17bebb0df7a0e # v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .deploy/${{ inputs.naiserator_file }}
          VARS: .deploy/${{ inputs.cluster }}-${{ inputs.namespace }}.json
      - name: Login GAR
        uses: nais/login@104bca34b70d1d00fe837bcd0689633978eca744 # ratchet:nais/login@v0
        if: inputs.gar == 'true'
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: teamforeldrepenger
      - name: Deploy ${{ inputs.cluster }} fra GAR
        if: inputs.gar == 'true'
        uses: nais/deploy/actions/deploy@afaaf1c0eecfa18daad98677b9d17bebb0df7a0e # v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: ${{ inputs.cluster }}
          IMAGE: ${{ steps.login.outputs.registry }}/${{ github.repository }}${{ inputs.image_suffix }}:${{ inputs.image }}
          RESOURCE: .deploy/${{ inputs.naiserator_file }}
          VARS: .deploy${{ inputs.deploy_context }}/${{ inputs.cluster }}-${{ inputs.namespace }}.json
