name: Deploy
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119)'
      cluster:
        required: true
        type: string
        description: 'The cluster to deploy to (dev-fss|dev-gcp|prod-fss|prod-gcp)'
      namespace:
        required: false
        type: string
        description: 'The namespace to deploy to'
        default: 'teamforeldrepenger'
      gar:
        required: false
        type: string
        description: 'The namespace to deploy to'
        default: 'false'
      naiserator_file:
        required: false
        type: string
        description: 'The naiserator.yaml file name in .deploy/ to use'
        default: 'naiserator.yaml'
      app:
        required: false
        type: string
        description: 'The app to be deployed in a monorepo setup - must start with /'
        default: ''
env:
  IMAGE: ${{ inputs.image }} # Brukes i naiserator.yaml
jobs:
  deploy:
    name: deploy
    environment: ${{ inputs.cluster }}:${{ inputs.namespace }}${{ inputs.app }}
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # ratchet:actions/checkout@v4
      - name: Deploy ${{ inputs.cluster }} fra Github
        if: inputs.gar == 'false'
        uses: nais/deploy/actions/deploy@0bca2c7e607d30fd757a2a23fb7d07b3ff96d540 # ratchet:nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .deploy/${{ inputs.naiserator_file }}
          VARS: .deploy/${{ inputs.cluster }}-${{ inputs.namespace }}.json
      - name: Login GAR
        uses: nais/login@104bca34b70d1d00fe837bcd0689633978eca744 # ratchet:nais/login@v0
        if: inputs.gar == 'true'
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: teamforeldrepenger
      - name: Deploy ${{ inputs.cluster }} fra GAR
        if: inputs.gar == 'true'
        uses: nais/deploy/actions/deploy@0bca2c7e607d30fd757a2a23fb7d07b3ff96d540 # ratchet:nais/deploy/actions/deploy@v1
        env:
          PRINT_PAYLOAD: true
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.cluster }}
          IMAGE: ${{ steps.login.outputs.registry }}/${{ github.repository }}${{ inputs.app }}:${{ inputs.image }}
          RESOURCE: .deploy/${{ inputs.naiserator_file }}
          VARS: .deploy${{ inputs.app }}/${{ inputs.cluster }}-${{ inputs.namespace }}.json
