name: Release feature
on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
        description: 'The release version.'
      java-version:
        required: false
        type: string
        description: 'Java SDK versjon som skal brukes.'
        default: '17'
      mvn-projects:
        required: false
        type: string
        description: 'Comma-delimited list of specified reactor projects to build instead of all projects.'
        default: ''
      release-profiles:
        required: false
        type: string
        description: 'Profiles which should be used when releasing an artifact.'
        default: '-Pdeploy'
      release-branch:
        required: false
        type: string
        description: 'Hvilken branch skal releases. Default master.'
        default: 'master'
      release-file:
        required: false
        type: string
        description: 'Hvilken pom.xml fil skal releases. Default empty.'
        default: ''
jobs:
  build:
    name: Release
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.release-branch }}
      - name: Setup java and maven
        uses: navikt/fp-gha-workflows/.github/actions/setup-java-and-maven@main # ratchet:exclude
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: ${{ inputs.java-version }}
      - name: Publish artifacts
        run: |
          mvn -B -s settings.xml versions:set -DnewVersion=${{ inputs.release-version }} ${{ inputs.release-file }}
          mvn -B -s settings.xml -DskipTests clean deploy ${{ inputs.mvn-projects }} ${{ inputs.release-profiles }} ${{ inputs.release-file }}
