name: Release feature

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: 'Java SDK versjon som skal brukes.'
        default: '17'
      mvn-projects:
        required: false
        type: string
        description: 'Comma-delimited list of specified reactor projects to build instead of all projects.'
        default: ''
      release-version:
        required: true
        type: string
        description: 'The release version.'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Create maven .m2 settings
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{"id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}",
              "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }}]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
          output_file: settings.xml

      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Publish artifacts
        run: |
          mvn -B -s settings.xml versions:set -DnewVersion=${{ inputs.release-version }}
          mvn -B -s settings.xml clean deploy ${{ inputs.mvn-projects }}
