name: Snyk

on:
  workflow_call:
    inputs:
      build-version:
        required: true
        type: string
        description: 'Build version of the produced image.'
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: '17'

jobs:
  snyk-monitor-docker:
    name: Docker
    if: github.ref_name == 'master'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Run Snyk to check Docker images for vulnerabilities
        if: false
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/${{ github.repository }}:latest
          args: --file=Dockerfile --org=teamforeldrepenger --severity-threshold=critical --project-name=${{ github.repository }}

      - name: Upload result to GitHub Code Scanning
        if: false
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'snyk.sarif'

      - name: Run Trivy vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        if: success()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  snyk-monitor-code:
    name: Code
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Set up JDK-${{ inputs.java-version }} with cache
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - uses: snyk/actions/setup@master

      - name: Create maven .m2 settings
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{
              "id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}",
              "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }
            }]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.READER_TOKEN }}" }]'
          output_file: settings.xml

      - name: Build
        run: |
          echo "Building ${{ inputs.build-version }}"
          mvn -B -s settings.xml versions:set -DnewVersion=${{ inputs.build-version }}
          mvn install -q -B -s settings.xml -DskipTests

      - name: Run Snyk monitor
        if: github.ref_name == 'master'
        run: >
          snyk monitor
          --org=teamforeldrepenger
          --all-projects
          --configuration-attributes=usage:java-runtime
          --severity-threshold=high
          --remote-repo-url=https://github.com/${{ github.repository }}.git
          -- -s settings.xml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        if: github.ref_name != 'master'
        run: >
          snyk test
          --org=teamforeldrepenger
          --all-projects
          --configuration-attributes=usage:java-runtime
          --severity-threshold=critical
          --remote-repo-url=https://github.com/${{ github.repository }}.git
          -- -s settings.xml
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
