name: Snyk og Trivy

on:
  workflow_call:
    inputs:
      build-version:
        required: true
        type: string
        description: 'Build version of the produced image.'
      java-version:
        required: false
        type: string
        description: Java SDK versjon som skal brukes.
        default: '17'
      publish-sarif:
        required: false
        type: boolean
        description: Skal trivy og snyk publisere sarif til code ql security?
        default: true
      multi-module-maven-project:
        required: false
        type: boolean
        description: Er det et multi module maven prosjekt?
        default: true

jobs:
  trivy-monitor-docker:
    name: Docker
    if: github.ref_name == 'master'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Henter image fra forrige steg
        run: docker pull ghcr.io/${{ github.repository }}:${{ inputs.build-version }}

      - name: Run Trivy vulnerability scanner non-public repo
        if: inputs.publish-sarif == 'false'
        uses: aquasecurity/trivy-action@master
        with:
          security-checks: 'vuln'
          image-ref: 'ghcr.io/${{ github.repository }}:${{ inputs.build-version }}'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Run Trivy vulnerability scanner for container
        if: inputs.publish-sarif
        uses: aquasecurity/trivy-action@master
        with:
          security-checks: 'vuln'
          image-ref: 'ghcr.io/${{ github.repository }}:${{ inputs.build-version }}'
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Upload Trivy scan results to GitHub Security tab
        if: always() && inputs.publish-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy.sarif'


  snyk-monitor-code:
    name: Code
    runs-on: 'ubuntu-latest'
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Create maven .m2 settings
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{"id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}",
              "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }},
              {"id": "github1", "name": "github1", "url": "https://maven.pkg.github.com/navikt/fp-felles",
              "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }}]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" },
                    { "id": "github1", "username": "${{ github.actor }}", "password": "${{ secrets.READER_TOKEN }}" }]'
          output_file: settings.xml

      - name: Set version
        run: |
          echo "Building ${{ inputs.build-version }}"
          mvn -q -B -s settings.xml versions:set -DnewVersion=${{ inputs.build-version }}

      - name: Legger til ekstra argumenter for snyk analyse
        if: inputs.multi-module-maven-project
        run: echo "EXTRA_ARGS=--maven-aggregate-project" >> $GITHUB_ENV

      - name: Run Snyk test
        uses: snyk/actions/maven@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >
            --severity-threshold=high
            --fail-on=all
            --org=teamforeldrepenger
            --project-name=${{ github.repository }}
            --remote-repo-url=https://github.com/${{ github.repository }}.git
            --sarif-file-output=snyk.sarif
            -- -s settings.xml -DskipTests ${{ env.EXTRA_ARGS }}

      - name: Upload result to GitHub Code Scanning
        if: always() && github.ref_name == 'master' && inputs.publish-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Run Snyk monitor
        if: github.ref_name == 'master'
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: >
            --severity-threshold=high
            --org=teamforeldrepenger
            --project-name=${{ github.repository }}
            --remote-repo-url=https://github.com/${{ github.repository }}.git
            -- -s settings.xml -DskipTests ${{ env.EXTRA_ARGS }}
