name: Snyk

on:
  workflow_call:
    inputs:
      upload-sarif:
        required: false
        type: boolean
        description: Upload result to GitHub Code Scanning
        default: false

jobs:
  snyk-monitor-code:
    name: Code
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        if: inputs.upload-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
